sonar.projectKey=my-ny-times
sonar.projectName=My New york Times
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml